default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  username: root
  password:
  host: localhost
  port: 3306

development:
  <<: *default
  database: anyperk_development

test:
  <<: *default
  database: anyperk_test
